targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      freezed:
        options:
          # Options for freezed
          union_key: runtimeType
          union_value_case: pascal
      riverpod_generator:
        options:
          # Options for riverpod_generator
          keepAlive: false