// Mocks generated by Mockito 5.4.5 from annotations
// in foot_step_meter/test/features/footprint_record/domain/usecase/route_recording_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:foot_step_meter/core/result.dart' as _i2;
import 'package:foot_step_meter/features/footprint_record/domain/entity/footprint_record.dart'
    as _i5;
import 'package:foot_step_meter/features/footprint_record/domain/entity/route.dart'
    as _i7;
import 'package:foot_step_meter/features/footprint_record/domain/error/location_error.dart'
    as _i10;
import 'package:foot_step_meter/features/footprint_record/domain/repository/footprint_record_repository.dart'
    as _i6;
import 'package:foot_step_meter/features/footprint_record/domain/repository/location_repository.dart'
    as _i3;
import 'package:foot_step_meter/features/footprint_record/domain/service/location_permission_service.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  @override
  _i4.Future<_i5.FootprintRecord?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i4.Future<_i5.FootprintRecord?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.FootprintRecord?>.value(),
      ) as _i4.Future<_i5.FootprintRecord?>);

  @override
  _i4.Stream<_i5.FootprintRecord> startLocationTracking() =>
      (super.noSuchMethod(
        Invocation.method(
          #startLocationTracking,
          [],
        ),
        returnValue: _i4.Stream<_i5.FootprintRecord>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.FootprintRecord>.empty(),
      ) as _i4.Stream<_i5.FootprintRecord>);

  @override
  _i4.Future<void> stopLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopLocationTracking,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [FootprintRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFootprintRecordRepository extends _i1.Mock
    implements _i6.FootprintRecordRepository {
  @override
  _i4.Future<void> saveFootprintRecord(_i5.FootprintRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFootprintRecord,
          [record],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveFootprintRecords(List<_i5.FootprintRecord>? records) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFootprintRecords,
          [records],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.FootprintRecord>> getFootprintRecordsByRoute(
          String? routeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFootprintRecordsByRoute,
          [routeId],
        ),
        returnValue: _i4.Future<List<_i5.FootprintRecord>>.value(
            <_i5.FootprintRecord>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.FootprintRecord>>.value(
            <_i5.FootprintRecord>[]),
      ) as _i4.Future<List<_i5.FootprintRecord>>);

  @override
  _i4.Future<List<_i5.FootprintRecord>> getAllFootprintRecords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFootprintRecords,
          [],
        ),
        returnValue: _i4.Future<List<_i5.FootprintRecord>>.value(
            <_i5.FootprintRecord>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.FootprintRecord>>.value(
            <_i5.FootprintRecord>[]),
      ) as _i4.Future<List<_i5.FootprintRecord>>);

  @override
  _i4.Future<void> deleteFootprintRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFootprintRecord,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFootprintRecordsByRoute(String? routeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFootprintRecordsByRoute,
          [routeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllFootprintRecords() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllFootprintRecords,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveRoute(_i7.Route? route) => (super.noSuchMethod(
        Invocation.method(
          #saveRoute,
          [route],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Route>> getAllRoutes() => (super.noSuchMethod(
        Invocation.method(
          #getAllRoutes,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Route>>.value(<_i7.Route>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Route>>.value(<_i7.Route>[]),
      ) as _i4.Future<List<_i7.Route>>);

  @override
  _i4.Future<_i7.Route?> getRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #getRoute,
          [routeId],
        ),
        returnValue: _i4.Future<_i7.Route?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.Route?>.value(),
      ) as _i4.Future<_i7.Route?>);

  @override
  _i4.Future<void> deleteRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [routeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllRoutes() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllRoutes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> exportRouteToJson(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #exportRouteToJson,
          [routeId],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportRouteToJson,
            [routeId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportRouteToJson,
            [routeId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> exportAllRoutesToJson() => (super.noSuchMethod(
        Invocation.method(
          #exportAllRoutesToJson,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportAllRoutesToJson,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportAllRoutesToJson,
            [],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [LocationPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationPermissionService extends _i1.Mock
    implements _i9.LocationPermissionService {
  @override
  _i4.Future<_i2.Result<void, _i10.LocationError>> checkLocationAccess() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLocationAccess,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i10.LocationError>>.value(
            _FakeResult_0<void, _i10.LocationError>(
          this,
          Invocation.method(
            #checkLocationAccess,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void, _i10.LocationError>>.value(
                _FakeResult_0<void, _i10.LocationError>(
          this,
          Invocation.method(
            #checkLocationAccess,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i10.LocationError>>);
}
