// Mocks generated by Mockito 5.4.5 from annotations
// in foot_step_meter/test/features/footprint_record/domain/usecase/start_location_tracking_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:foot_step_meter/core/result.dart' as _i2;
import 'package:foot_step_meter/features/footprint_record/domain/entity/footprint_record.dart'
    as _i5;
import 'package:foot_step_meter/features/footprint_record/domain/error/location_error.dart'
    as _i7;
import 'package:foot_step_meter/features/footprint_record/domain/repository/location_repository.dart'
    as _i3;
import 'package:foot_step_meter/features/footprint_record/domain/service/location_permission_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  @override
  _i4.Future<_i5.FootprintRecord?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i4.Future<_i5.FootprintRecord?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.FootprintRecord?>.value(),
      ) as _i4.Future<_i5.FootprintRecord?>);

  @override
  _i4.Stream<_i5.FootprintRecord> startLocationTracking() =>
      (super.noSuchMethod(
        Invocation.method(
          #startLocationTracking,
          [],
        ),
        returnValue: _i4.Stream<_i5.FootprintRecord>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.FootprintRecord>.empty(),
      ) as _i4.Stream<_i5.FootprintRecord>);

  @override
  _i4.Future<void> stopLocationTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopLocationTracking,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [LocationPermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationPermissionService extends _i1.Mock
    implements _i6.LocationPermissionService {
  @override
  _i4.Future<_i2.Result<void, _i7.LocationError>> checkLocationAccess() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLocationAccess,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i7.LocationError>>.value(
            _FakeResult_0<void, _i7.LocationError>(
          this,
          Invocation.method(
            #checkLocationAccess,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void, _i7.LocationError>>.value(
                _FakeResult_0<void, _i7.LocationError>(
          this,
          Invocation.method(
            #checkLocationAccess,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i7.LocationError>>);
}
